// GPL-3.0-or-later
// Copyright 2024--present rsx-rs developers

//! Statistical functions: chi-squared test with Yates correction,
//! Bonferroni multiple testing correction, and group bias.

use std::fmt;

/// Format a float like C++ `operator<<` default: `%g` with 6 significant digits.
/// This matches the C++ radsex output format exactly.
pub struct Cg(pub f64);

impl fmt::Display for Cg {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        // %g with 6 significant digits, strip trailing zeros
        let val = self.0;
        if val == 0.0 {
            return write!(f, "0");
        }
        let abs = val.abs();
        let exp = abs.log10().floor() as i32;
        if (-4..6).contains(&exp) {
            // Fixed notation
            let precision = (5 - exp).max(0) as usize;
            let formatted = format!("{:.*}", precision, val);
            // Strip trailing zeros after decimal point
            if formatted.contains('.') {
                let trimmed = formatted.trim_end_matches('0').trim_end_matches('.');
                write!(f, "{trimmed}")
            } else {
                write!(f, "{formatted}")
            }
        } else {
            // Scientific notation
            let mantissa = val / 10f64.powi(exp);
            let formatted = format!("{:.5}", mantissa);
            let trimmed = formatted.trim_end_matches('0').trim_end_matches('.');
            write!(f, "{trimmed}e{exp:+03}")
        }
    }
}

/// Chi-squared statistic with Yates continuity correction for a 2x2 table.
///
/// Implements the shortcut formula:
///   chi2 = N * (|ad - bc| - N/2)^2 / (a+b)(c+d)(a+c)(b+d)
///
/// where the contingency table is:
///   |           | marker present | marker absent |
///   |-----------|----------------|---------------|
///   | group1    | n_group1       | total1 - n1   |
///   | group2    | n_group2       | total2 - n2   |
pub fn chi_squared_yates(
    n_group1: u32,
    n_group2: u32,
    total_group1: u32,
    total_group2: u32,
) -> f64 {
    let n = (total_group1 + total_group2) as f64;
    let ns = total_group1 as f64;
    let nf = total_group2 as f64;
    let na = (n_group1 + n_group2) as f64;
    let nb = n - na;

    let ad_bc = ((n_group1 as i64) * (total_group2 as i64)
        - (n_group2 as i64) * (total_group1 as i64))
        .unsigned_abs() as f64;
    let yates = (ad_bc - n / 2.0).max(0.0);

    n * yates * yates / (ns * nf * na * nb)
}

/// P-value for a chi-squared statistic with df=1.
///
/// Uses the exact identity: for df=1, the chi-squared CDF is
///   P(chi2) = erf(sqrt(chi2/2))
/// so the p-value is:
///   p = 1 - P(chi2) = erfc(sqrt(chi2/2))
///
/// This replaces the full regularized gamma function with a single
/// libm erfc call. Derived via SymPy:
///   gamma(1/2, x) = sqrt(pi) * erf(sqrt(x))
///   Gamma(1/2) = sqrt(pi)
///   P(1/2, x) = erf(sqrt(x))
///   p = erfc(sqrt(chi2/2))
pub fn chi_squared_p(chi_sq: f64) -> f64 {
    if chi_sq.is_nan() || chi_sq <= 0.0 {
        return 1.0;
    }
    fast_erfc((chi_sq / 2.0).sqrt()).min(1.0)
}

/// erfc(t) via libm (CPU-optimized, ~30ns).
/// For GPU kernels, use `fast_erfc_poly` which avoids libm calls.
#[inline]
fn fast_erfc(t: f64) -> f64 {
    libm::erfc(t)
}

/// Sollya-generated minimax polynomial for erfc(t) on [0, 6].
/// Single degree-40 polynomial -- branchless, no exp(), GPU/SIMD ready.
/// Max absolute error: 8.2e-17 (below f64 epsilon).
/// See `scripts/sollya/erfc_direct.sollya`.
#[inline]
#[allow(dead_code)]
pub fn fast_erfc_poly(t: f64) -> f64 {
    if t >= 6.0 {
        return 0.0;
    }
    horner(t, &ERFC_POLY)
}

/// Horner evaluation: P(x) = c[0] + x*(c[1] + x*(c[2] + ...))
/// Uses FMA (mul_add) for maximum precision and speed.
#[inline]
fn horner(x: f64, coeffs: &[f64]) -> f64 {
    let mut result = 0.0f64;
    for &c in coeffs.iter().rev() {
        result = result.mul_add(x, c);
    }
    result
}

// Sollya remez degree-40 minimax polynomial for erfc(t) on [0, 6].
// Max abs error: 8.22e-17. No exp() call. SIMD/GPU friendly.
// Coefficients as hex float via hexf! -- direct Sollya output, zero transcription error.
// Generated by: cd scripts && pixi run minimax-direct
#[rustfmt::skip]
const ERFC_POLY: [f64; 41] = [
    hexf::hexf64!("0x1.fffffffffffffp-1"),   // c0
    hexf::hexf64!("-0x1.20dd750429abbp0"),    // c1
    hexf::hexf64!("-0x1.b83ea9b36d55dp-39"),  // c2
    hexf::hexf64!("0x1.812746b1e8a4cp-2"),    // c3
    hexf::hexf64!("-0x1.c01f0b102e8eep-30"),  // c4
    hexf::hexf64!("-0x1.ce2f1d3ee338ep-4"),   // c5
    hexf::hexf64!("-0x1.c92fce83a23c7p-24"),  // c6
    hexf::hexf64!("0x1.b82ed8ff9fbe4p-6"),    // c7
    hexf::hexf64!("-0x1.6af32fff4be83p-20"),  // c8
    hexf::hexf64!("-0x1.56386821f01b1p-8"),   // c9
    hexf::hexf64!("0x1.84dc6b9cac39ap-20"),   // c10
    hexf::hexf64!("0x1.b5ac4763df8f1p-11"),   // c11
    hexf::hexf64!("0x1.226e298aa6414p-14"),   // c12
    hexf::hexf64!("-0x1.24f7e6a2b2ceap-12"),  // c13
    hexf::hexf64!("0x1.239ab445441dcp-12"),   // c14
    hexf::hexf64!("-0x1.8b31805e161c4p-12"),  // c15
    hexf::hexf64!("0x1.dee4be601e3e9p-12"),   // c16
    hexf::hexf64!("-0x1.d77acde978739p-12"),  // c17
    hexf::hexf64!("0x1.883aaa14debap-12"),    // c18
    hexf::hexf64!("-0x1.18dadbd5cc3abp-12"),  // c19
    hexf::hexf64!("0x1.5b8d481772fb4p-13"),   // c20
    hexf::hexf64!("-0x1.74855604ef48ap-14"),  // c21
    hexf::hexf64!("0x1.5acc93d93d3b4p-15"),   // c22
    hexf::hexf64!("-0x1.18f50a2c68becp-16"),  // c23
    hexf::hexf64!("0x1.8c5fd35d0866cp-18"),   // c24
    hexf::hexf64!("-0x1.e6a1ce3798ffap-20"),  // c25
    hexf::hexf64!("0x1.03a13e31b65dp-21"),    // c26
    hexf::hexf64!("-0x1.e0be7f87c8eaep-24"),  // c27
    hexf::hexf64!("0x1.815459515f217p-26"),   // c28
    hexf::hexf64!("-0x1.0a9d538fdfb12p-28"),  // c29
    hexf::hexf64!("0x1.3d4235505e0e1p-31"),   // c30
    hexf::hexf64!("-0x1.42ee4b10402d8p-34"),  // c31
    hexf::hexf64!("0x1.172dd0bdac958p-37"),   // c32
    hexf::hexf64!("-0x1.960c57cfddb97p-41"),  // c33
    hexf::hexf64!("0x1.ea4beaf5f9701p-45"),   // c34
    hexf::hexf64!("-0x1.e2a4b9cf888a5p-49"),  // c35
    hexf::hexf64!("0x1.796af39619721p-53"),   // c36
    hexf::hexf64!("-0x1.c31352aaa9451p-58"),  // c37
    hexf::hexf64!("0x1.82f8c94463357p-63"),   // c38
    hexf::hexf64!("-0x1.a861a25d26dp-69"),    // c39
    hexf::hexf64!("0x1.bef061298bc36p-76"),   // c40
];

/// Compute p-value of association with group using chi-squared test
/// with Yates correction. Matches C++ `get_p_association` exactly.
pub fn p_association(n_group1: u32, n_group2: u32, total_group1: u32, total_group2: u32) -> f64 {
    let chi_sq = chi_squared_yates(n_group1, n_group2, total_group1, total_group2);

    // NaN guard: if chi_sq is NaN (e.g. division by zero when marker
    // is present in all individuals), return p = 1.0
    let p = if chi_sq.is_nan() {
        1.0
    } else {
        chi_squared_p(chi_sq).min(1.0)
    };

    // Lower bound: 1e-16 (matching C++ behavior)
    p.max(1e-16)
}

/// Apply Bonferroni correction to a p-value.
pub fn bonferroni_correct(p: f64, n_markers: u64) -> f64 {
    (p * n_markers as f64).min(1.0)
}

/// Group bias: difference in marker frequency between two groups.
/// Ranges from -1.0 (only in group2) to +1.0 (only in group1).
pub fn group_bias(n_group1: u32, total_group1: u32, n_group2: u32, total_group2: u32) -> f64 {
    (n_group1 as f64 / total_group1 as f64) - (n_group2 as f64 / total_group2 as f64)
}

/// Find median of a mutable slice (partially sorts in-place).
pub fn find_median(data: &mut [u16]) -> u16 {
    let len = data.len();
    if len == 0 {
        return 0;
    }
    data.sort_unstable();
    if len % 2 == 0 {
        let a = data[len / 2 - 1] as u32;
        let b = data[len / 2] as u32;
        ((a + b) / 2) as u16
    } else {
        data[len / 2]
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_chi_squared_known_values() {
        // 10 males with marker, 0 females, out of 15 males and 10 females
        let chi_sq = chi_squared_yates(10, 0, 15, 10);
        assert!(chi_sq > 0.0);
        let p = chi_squared_p(chi_sq);
        assert!(p < 0.05);
    }

    #[test]
    fn test_equal_distribution_not_significant() {
        // 5 males, 5 females, out of 10 each -- no association
        let p = p_association(5, 5, 10, 10);
        assert!(p > 0.05);
    }

    #[test]
    fn test_p_association_floor() {
        // Extreme case: should be capped at 1e-16
        let p = p_association(20, 0, 20, 20);
        assert!(p >= 1e-16);
    }

    #[test]
    fn test_bonferroni() {
        assert_eq!(bonferroni_correct(0.01, 10), 0.1);
        assert_eq!(bonferroni_correct(0.5, 10), 1.0); // capped at 1.0
    }

    #[test]
    fn test_group_bias() {
        let bias = group_bias(10, 10, 0, 10);
        assert!((bias - 1.0).abs() < f64::EPSILON);
        let bias = group_bias(0, 10, 10, 10);
        assert!((bias - (-1.0)).abs() < f64::EPSILON);
    }

    #[test]
    fn test_find_median_odd() {
        let mut data = vec![3, 1, 2];
        assert_eq!(find_median(&mut data), 2);
    }

    #[test]
    fn test_find_median_even() {
        let mut data = vec![4, 1, 3, 2];
        assert_eq!(find_median(&mut data), 2); // (2+3)/2 = 2 (integer division)
    }
}
