// GPL-3.0-or-later
// Copyright 2024--present rsx-rs developers

//! Statistical functions: chi-squared test with Yates correction,
//! Bonferroni multiple testing correction, and group bias.

use std::fmt;

/// Format a float like C++ `operator<<` default: `%g` with 6 significant digits.
/// This matches the C++ radsex output format exactly.
pub struct Cg(pub f64);

impl fmt::Display for Cg {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        // %g with 6 significant digits, strip trailing zeros
        let val = self.0;
        if val == 0.0 {
            return write!(f, "0");
        }
        let abs = val.abs();
        let exp = abs.log10().floor() as i32;
        if (-4..6).contains(&exp) {
            // Fixed notation
            let precision = (5 - exp).max(0) as usize;
            let formatted = format!("{:.*}", precision, val);
            // Strip trailing zeros after decimal point
            if formatted.contains('.') {
                let trimmed = formatted.trim_end_matches('0').trim_end_matches('.');
                write!(f, "{trimmed}")
            } else {
                write!(f, "{formatted}")
            }
        } else {
            // Scientific notation
            let mantissa = val / 10f64.powi(exp);
            let formatted = format!("{:.5}", mantissa);
            let trimmed = formatted.trim_end_matches('0').trim_end_matches('.');
            write!(f, "{trimmed}e{exp:+03}")
        }
    }
}

/// Chi-squared statistic with Yates continuity correction for a 2x2 table.
///
/// Implements the shortcut formula:
///   chi2 = N * (|ad - bc| - N/2)^2 / (a+b)(c+d)(a+c)(b+d)
///
/// where the contingency table is:
///   |           | marker present | marker absent |
///   |-----------|----------------|---------------|
///   | group1    | n_group1       | total1 - n1   |
///   | group2    | n_group2       | total2 - n2   |
pub fn chi_squared_yates(
    n_group1: u32,
    n_group2: u32,
    total_group1: u32,
    total_group2: u32,
) -> f64 {
    let n = (total_group1 + total_group2) as f64;
    let ns = total_group1 as f64;
    let nf = total_group2 as f64;
    let na = (n_group1 + n_group2) as f64;
    let nb = n - na;

    let ad_bc = ((n_group1 as i64) * (total_group2 as i64)
        - (n_group2 as i64) * (total_group1 as i64))
        .unsigned_abs() as f64;
    let yates = (ad_bc - n / 2.0).max(0.0);

    n * yates * yates / (ns * nf * na * nb)
}

/// P-value for a chi-squared statistic with df=1.
///
/// Uses the exact identity: for df=1, the chi-squared CDF is
///   P(chi2) = erf(sqrt(chi2/2))
/// so the p-value is:
///   p = 1 - P(chi2) = erfc(sqrt(chi2/2))
///
/// This replaces the full regularized gamma function with a single
/// libm erfc call. Derived via SymPy:
///   gamma(1/2, x) = sqrt(pi) * erf(sqrt(x))
///   Gamma(1/2) = sqrt(pi)
///   P(1/2, x) = erf(sqrt(x))
///   p = erfc(sqrt(chi2/2))
pub fn chi_squared_p(chi_sq: f64) -> f64 {
    if chi_sq.is_nan() || chi_sq <= 0.0 {
        return 1.0;
    }
    fast_erfc((chi_sq / 2.0).sqrt()).min(1.0)
}

/// Sollya-generated minimax polynomial approximation of erfc(t).
///
/// Three regions with `fpminimax`-optimized coefficients (hex float,
/// bit-exact IEEE 754 double). See `scripts/sollya/erfc_minimax.sollya`.
///
/// Region 1 [0, 0.5]:   degree 20, max relerr 2.04e-20
/// Region 2 [0.5, 4]:   degree 25, max relerr 6.08e-17
/// Region 3 [4, 8]:     degree 12, max relerr 1.09e-11 (transformed)
/// Beyond t=8:          erfc < 1e-29, return 0 (below p-value floor)
///
/// Branching version for CPU. A branchless (predicated) version for
/// GPU/SIMD would compute all three regions and blend with masks.
#[inline]
fn fast_erfc(t: f64) -> f64 {
    if t < 0.5 {
        horner(t, &ERFC_R1)
    } else if t < 4.0 {
        horner(t, &ERFC_R2) * libm::exp(-t * t)
    } else if t < 8.0 {
        horner(t, &ERFC_R3) * libm::exp(-t * t) / (t * SQRT_PI)
    } else {
        0.0
    }
}

const SQRT_PI: f64 = 1.7724538509055159; // sqrt(pi)

/// Horner evaluation: P(x) = c[0] + x*(c[1] + x*(c[2] + ...))
#[inline]
fn horner(x: f64, coeffs: &[f64]) -> f64 {
    let mut result = 0.0f64;
    for &c in coeffs.iter().rev() {
        result = result.mul_add(x, c);
    }
    result
}

// Sollya fpminimax coefficients -- bit-exact IEEE 754 double.
// Generated by: cd scripts && pixi run minimax
// Coefficients are f64::from_bits(hex) for zero transcription error.

#[rustfmt::skip]
const ERFC_R1: [f64; 21] = [
    f64::from_bits(0x3FF0000000000000), f64::from_bits(0xBFF20DD750429B6D),
    f64::from_bits(0xBCF0EE366949322F), f64::from_bits(0x3FD812746B039270),
    f64::from_bits(0xBDB2F10B5ED90D84), f64::from_bits(0xBFBCE2F217C0C3F4),
    f64::from_bits(0xBE47563E71D71D7B), f64::from_bits(0x3F9B82D8E4DAE605),
    f64::from_bits(0xBEBCF92368C41425), f64::from_bits(0xBF7556E6866A9C0B),
    f64::from_bits(0xBF176390164CA37B), f64::from_bits(0x3F552D09E8035D92),
    f64::from_bits(0xBF5B82BE59FEBBD9), f64::from_bits(0x3F7427F2A845D970),
    f64::from_bits(0xBF882402EA65793F), f64::from_bits(0x3F95BE80237EB99A),
    f64::from_bits(0xBF9D83D8EA7BE04A), f64::from_bits(0x3F9D3DE673D03FF0),
    f64::from_bits(0xBF93EF5E78F1A3B4), f64::from_bits(0x3F80B65E89649E40),
    f64::from_bits(0xBF59F7FBB5A70B88),
];

#[rustfmt::skip]
const ERFC_R2: [f64; 26] = [
    f64::from_bits(0x3FEFFFFFFE0ACAEB), f64::from_bits(0xBFF20DD73E167032),
    f64::from_bits(0x3FEFFFFEC279B625), f64::from_bits(0xBFE8126DA0253F75),
    f64::from_bits(0x3FDFFFCB9689DB2D), f64::from_bits(0xBFD3415EEB984BE4),
    f64::from_bits(0x3FC552A623D054E0), f64::from_bits(0xBFB5F87C9BD32CB2),
    f64::from_bits(0x3FA5384726CC9AA8), f64::from_bits(0xBF9348426071F0CA),
    f64::from_bits(0x3F807B0D58A482D8), f64::from_bits(0xBF6A60DB39BCA0CD),
    f64::from_bits(0x3F5398D8267C7BEF), f64::from_bits(0xBF3AB78D6C53D560),
    f64::from_bits(0x3F207C2E5ACE77FE), f64::from_bits(0xBF0226E06424FA30),
    f64::from_bits(0x3EE1931850BC3814), f64::from_bits(0xBEBD7A4ABEBE946A),
    f64::from_bits(0x3E9512DC4B408E64), f64::from_bits(0xBE69396E7B7B8D2D),
    f64::from_bits(0x3E38B9B53D33F90B), f64::from_bits(0xBE0348AEB325567E),
    f64::from_bits(0x3DC6F9420444D102), f64::from_bits(0xBD839A4610ED7B88),
    f64::from_bits(0x3D354F2A99DA4A9F), f64::from_bits(0xBCD6266F34EF743B),
];

#[rustfmt::skip]
const ERFC_R3: [f64; 13] = [
    f64::from_bits(0x3FD38A0C0B13D1FB), f64::from_bits(0x3FEA6D9F47316061),
    f64::from_bits(0xBFE10A635E21CCD3), f64::from_bits(0x3FCD3D691596725E),
    f64::from_bits(0xBFB1EF2AC487C434), f64::from_bits(0x3F903EC5D593AD13),
    f64::from_bits(0xBF66051F16A0E43D), f64::from_bits(0x3F365462A6054BBD),
    f64::from_bits(0xBF00B9D92264D7B0), f64::from_bits(0x3EC1FC2C9D585068),
    f64::from_bits(0xBE7A485F15143041), f64::from_bits(0x3E2763790837EBD3),
    f64::from_bits(0xBDC324250A1A9B52),
];

/// Compute p-value of association with group using chi-squared test
/// with Yates correction. Matches C++ `get_p_association` exactly.
pub fn p_association(n_group1: u32, n_group2: u32, total_group1: u32, total_group2: u32) -> f64 {
    let chi_sq = chi_squared_yates(n_group1, n_group2, total_group1, total_group2);

    // NaN guard: if chi_sq is NaN (e.g. division by zero when marker
    // is present in all individuals), return p = 1.0
    let p = if chi_sq.is_nan() {
        1.0
    } else {
        chi_squared_p(chi_sq).min(1.0)
    };

    // Lower bound: 1e-16 (matching C++ behavior)
    p.max(1e-16)
}

/// Apply Bonferroni correction to a p-value.
pub fn bonferroni_correct(p: f64, n_markers: u64) -> f64 {
    (p * n_markers as f64).min(1.0)
}

/// Group bias: difference in marker frequency between two groups.
/// Ranges from -1.0 (only in group2) to +1.0 (only in group1).
pub fn group_bias(n_group1: u32, total_group1: u32, n_group2: u32, total_group2: u32) -> f64 {
    (n_group1 as f64 / total_group1 as f64) - (n_group2 as f64 / total_group2 as f64)
}

/// Find median of a mutable slice (partially sorts in-place).
pub fn find_median(data: &mut [u16]) -> u16 {
    let len = data.len();
    if len == 0 {
        return 0;
    }
    data.sort_unstable();
    if len % 2 == 0 {
        let a = data[len / 2 - 1] as u32;
        let b = data[len / 2] as u32;
        ((a + b) / 2) as u16
    } else {
        data[len / 2]
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_chi_squared_known_values() {
        // 10 males with marker, 0 females, out of 15 males and 10 females
        let chi_sq = chi_squared_yates(10, 0, 15, 10);
        assert!(chi_sq > 0.0);
        let p = chi_squared_p(chi_sq);
        assert!(p < 0.05);
    }

    #[test]
    fn test_equal_distribution_not_significant() {
        // 5 males, 5 females, out of 10 each -- no association
        let p = p_association(5, 5, 10, 10);
        assert!(p > 0.05);
    }

    #[test]
    fn test_p_association_floor() {
        // Extreme case: should be capped at 1e-16
        let p = p_association(20, 0, 20, 20);
        assert!(p >= 1e-16);
    }

    #[test]
    fn test_bonferroni() {
        assert_eq!(bonferroni_correct(0.01, 10), 0.1);
        assert_eq!(bonferroni_correct(0.5, 10), 1.0); // capped at 1.0
    }

    #[test]
    fn test_group_bias() {
        let bias = group_bias(10, 10, 0, 10);
        assert!((bias - 1.0).abs() < f64::EPSILON);
        let bias = group_bias(0, 10, 10, 10);
        assert!((bias - (-1.0)).abs() < f64::EPSILON);
    }

    #[test]
    fn test_find_median_odd() {
        let mut data = vec![3, 1, 2];
        assert_eq!(find_median(&mut data), 2);
    }

    #[test]
    fn test_find_median_even() {
        let mut data = vec![4, 1, 3, 2];
        assert_eq!(find_median(&mut data), 2); // (2+3)/2 = 2 (integer division)
    }
}
