// GPL-3.0-or-later
// Copyright 2024--present rsx-rs developers

//! CLI for RADSex: sex-determination analysis from RAD-Sequencing data.

use clap::{Parser, Subcommand};
use rsx_core::commands;

#[derive(Parser)]
#[command(name = "rsx", about = "rsx: sex-determination from RAD-seq data")]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    /// Compute a table of marker depths from demultiplexed reads files
    Process {
        /// Path to directory containing demultiplexed sequence files
        #[arg(short = 'i', long = "input-dir")]
        input_dir: String,
        /// Path to the output file
        #[arg(short = 'o', long = "output-file")]
        output_file: String,
        /// Number of threads to use
        #[arg(short = 'T', long = "threads", default_value = "1")]
        threads: u32,
        /// Minimum depth in at least one individual to retain a marker
        #[arg(short = 'd', long = "min-depth", default_value = "1")]
        min_depth: u16,
        /// Deduplicate markers by canonical k-mer of this size (optional)
        #[arg(short = 'k', long = "kmer-dedup")]
        kmer_dedup: Option<usize>,
    },

    /// Compute the distribution of markers between group1 and group2
    Distrib {
        /// Path to a marker depths table generated by "process"
        #[arg(short = 't', long = "markers-table")]
        markers_table: String,
        /// Path to a population map file
        #[arg(short = 'p', long = "popmap")]
        popmap: String,
        /// Path to the output file
        #[arg(short = 'o', long = "output-file")]
        output_file: String,
        /// Minimum depth to consider a marker present
        #[arg(short = 'd', long = "min-depth", default_value = "1")]
        min_depth: u16,
        /// Names of groups to compare (comma-separated)
        #[arg(short = 'G', long = "groups", value_delimiter = ',')]
        groups: Option<Vec<String>>,
        /// P-value significance threshold
        #[arg(short = 'S', long = "signif-threshold", default_value = "0.05")]
        signif_threshold: f32,
        /// Disable Bonferroni correction
        #[arg(short = 'C', long = "disable-correction")]
        disable_correction: bool,
    },

    /// Extract markers significantly associated with a group
    Signif {
        /// Path to a marker depths table
        #[arg(short = 't', long = "markers-table")]
        markers_table: String,
        /// Path to a population map file
        #[arg(short = 'p', long = "popmap")]
        popmap: String,
        /// Path to the output file
        #[arg(short = 'o', long = "output-file")]
        output_file: String,
        /// Minimum depth to consider a marker present
        #[arg(short = 'd', long = "min-depth", default_value = "1")]
        min_depth: u16,
        /// Names of groups to compare
        #[arg(short = 'G', long = "groups", value_delimiter = ',')]
        groups: Option<Vec<String>>,
        /// P-value significance threshold
        #[arg(short = 'S', long = "signif-threshold", default_value = "0.05")]
        signif_threshold: f32,
        /// Multiple testing correction: bonferroni (default), fdr, none
        #[arg(long = "correction", default_value = "bonferroni")]
        correction: String,
        /// Statistical test: chisq (default), fisher, gtest
        #[arg(long = "test", default_value = "chisq")]
        test_method: String,
        /// Output in FASTA format instead of table format
        #[arg(short = 'a', long = "output-fasta")]
        output_fasta: bool,
        /// Include Bayes Factor and posterior P(sex-linked) in output
        #[arg(long = "bayes")]
        output_bayes: bool,
    },

    /// Compute marker frequencies in all individuals
    Freq {
        /// Path to a marker depths table
        #[arg(short = 't', long = "markers-table")]
        markers_table: String,
        /// Path to the output file
        #[arg(short = 'o', long = "output-file")]
        output_file: String,
        /// Minimum depth to consider a marker present
        #[arg(short = 'd', long = "min-depth", default_value = "1")]
        min_depth: u16,
    },

    /// Compute number of retained reads for each individual
    Depth {
        /// Path to a marker depths table
        #[arg(short = 't', long = "markers-table")]
        markers_table: String,
        /// Path to a population map file
        #[arg(short = 'p', long = "popmap")]
        popmap: String,
        /// Path to the output file
        #[arg(short = 'o', long = "output-file")]
        output_file: String,
        /// Minimum frequency of a marker to retain it
        #[arg(short = 'f', long = "min-frequency", default_value = "0.75")]
        min_frequency: f32,
    },

    /// Align markers to a genome and compute metrics
    #[cfg(feature = "map")]
    Map {
        /// Path to a markers file (depth table or FASTA)
        #[arg(short = 't', long = "markers-file")]
        markers_file: String,
        /// Path to the output file
        #[arg(short = 'o', long = "output-file")]
        output_file: String,
        /// Path to a population map file
        #[arg(short = 'p', long = "popmap")]
        popmap: String,
        /// Path to the genome file in FASTA format
        #[arg(short = 'g', long = "genome-file")]
        genome_file: String,
        /// Minimum depth to consider a marker present
        #[arg(short = 'd', long = "min-depth", default_value = "1")]
        min_depth: u16,
        /// Names of groups to compare
        #[arg(short = 'G', long = "groups", value_delimiter = ',')]
        groups: Option<Vec<String>>,
        /// Minimum mapping quality
        #[arg(short = 'q', long = "min-quality", default_value = "20")]
        min_quality: u32,
        /// Minimum frequency of individuals to retain a marker
        #[arg(short = 'Q', long = "min-frequency", default_value = "0.1")]
        min_frequency: f32,
        /// P-value significance threshold
        #[arg(short = 'S', long = "signif-threshold", default_value = "0.05")]
        signif_threshold: f32,
        /// Disable Bonferroni correction
        #[arg(short = 'C', long = "disable-correction")]
        disable_correction: bool,
    },

    /// Extract a subset of a marker depths table
    Subset {
        /// Path to a marker depths table
        #[arg(short = 't', long = "markers-table")]
        markers_table: String,
        /// Path to a population map file
        #[arg(short = 'p', long = "popmap")]
        popmap: String,
        /// Path to the output file
        #[arg(short = 'o', long = "output-file")]
        output_file: String,
        /// Minimum depth to consider a marker present
        #[arg(short = 'd', long = "min-depth", default_value = "1")]
        min_depth: u16,
        /// Names of groups to compare
        #[arg(short = 'G', long = "groups", value_delimiter = ',')]
        groups: Option<Vec<String>>,
        /// P-value significance threshold
        #[arg(short = 'S', long = "signif-threshold", default_value = "0.05")]
        signif_threshold: f32,
        /// Disable Bonferroni correction
        #[arg(short = 'C', long = "disable-correction")]
        disable_correction: bool,
        /// Output in FASTA format
        #[arg(short = 'a', long = "output-fasta")]
        output_fasta: bool,
        /// Minimum individuals from group1
        #[arg(short = 'm', long = "min-group1", default_value = "0")]
        min_group1: u32,
        /// Minimum individuals from group2
        #[arg(short = 'n', long = "min-group2", default_value = "0")]
        min_group2: u32,
        /// Maximum individuals from group1
        #[arg(short = 'M', long = "max-group1", default_value = "9999")]
        max_group1: u32,
        /// Maximum individuals from group2
        #[arg(short = 'N', long = "max-group2", default_value = "9999")]
        max_group2: u32,
        /// Minimum total individuals
        #[arg(short = 'i', long = "min-individuals", default_value = "0")]
        min_individuals: u32,
        /// Maximum total individuals
        #[arg(short = 'I', long = "max-individuals", default_value = "9999")]
        max_individuals: u32,
    },

    /// Merge multiple marker depth tables by sequence identity
    Merge {
        /// Paths to input marker depth tables (positional, 2 or more)
        #[arg(required = true, num_args = 1..)]
        input_files: Vec<String>,
        /// Path to the output merged table
        #[arg(short = 'o', long = "output-file")]
        output_file: String,
        /// Number of entries to buffer before flushing to disk (default: 2M)
        #[arg(short = 'B', long = "buffer-size", default_value = "2000000")]
        buffer_size: usize,
        /// Output as Parquet instead of TSV (requires --features parquet-io)
        #[arg(long = "output-parquet")]
        output_parquet: bool,
    },

    /// Streaming PCA of the depth matrix (Tucker mode-2 decomposition)
    Pca {
        /// Path to a marker depths table
        #[arg(short = 't', long = "markers-table")]
        markers_table: String,
        /// Output directory for eigenvalues, loadings, summary
        #[arg(short = 'o', long = "output-dir")]
        output_dir: String,
        /// Minimum depth to consider a marker present
        #[arg(short = 'd', long = "min-depth", default_value = "1")]
        min_depth: u16,
        /// Number of principal components to output (default: all)
        #[arg(short = 'r', long = "components")]
        components: Option<usize>,
    },
}

fn extract_groups(groups: &Option<Vec<String>>) -> (String, String) {
    match groups {
        Some(g) if g.len() == 2 => (g[0].clone(), g[1].clone()),
        _ => (String::new(), String::new()),
    }
}

fn main() {
    env_logger::init();
    let cli = Cli::parse();

    let result: Result<(), Box<dyn std::error::Error>> = match cli.command {
        Commands::Process {
            input_dir,
            output_file,
            threads,
            min_depth,
            kmer_dedup,
        } => {
            let params = commands::process::ProcessParams {
                input_dir_path: input_dir,
                output_file_path: output_file,
                n_threads: threads,
                min_depth,
                kmer_dedup,
            };
            // Use MPI if available (feature-gated), else single-node rayon
            #[cfg(feature = "mpi")]
            { commands::process_mpi::run_mpi(&params) }
            #[cfg(not(feature = "mpi"))]
            { commands::process::run(&params) }
        }

        Commands::Distrib {
            markers_table,
            popmap,
            output_file,
            min_depth,
            ref groups,
            signif_threshold,
            disable_correction,
        } => {
            let (g1, g2) = extract_groups(groups);
            commands::distrib::run(&commands::distrib::DistribParams {
                markers_table_path: markers_table,
                popmap_file_path: popmap,
                output_file_path: output_file,
                min_depth,
                signif_threshold,
                correction: if disable_correction { rsx_core::test_method::CorrectionMethod::None } else { rsx_core::test_method::CorrectionMethod::Bonferroni },
                test_method: rsx_core::test_method::TestMethod::ChiSquared,
                output_bayes: false,
                group1: g1,
                group2: g2,
            })
        }

        Commands::Signif {
            markers_table,
            popmap,
            output_file,
            min_depth,
            ref groups,
            signif_threshold,
            correction,
            test_method,
            output_fasta,
            output_bayes,
        } => {
            let (g1, g2) = extract_groups(groups);
            let corr = rsx_core::test_method::CorrectionMethod::parse_str(&correction)
                .unwrap_or_else(|e| { log::error!("{e}"); std::process::exit(1); });
            let test = rsx_core::test_method::TestMethod::parse_str(&test_method)
                .unwrap_or_else(|e| { log::error!("{e}"); std::process::exit(1); });
            commands::signif::run(&commands::signif::SignifParams {
                markers_table_path: markers_table,
                popmap_file_path: popmap,
                output_file_path: output_file,
                min_depth,
                signif_threshold,
                correction: corr,
                test_method: test,
                output_fasta,
                output_bayes,
                group1: g1,
                group2: g2,
            })
        }

        Commands::Freq {
            markers_table,
            output_file,
            min_depth,
        } => commands::freq::run(&commands::freq::FreqParams {
            markers_table_path: markers_table,
            output_file_path: output_file,
            min_depth,
        }),

        Commands::Depth {
            markers_table,
            popmap,
            output_file,
            min_frequency,
        } => {
            // Auto-detect streaming: use external sort for files > 2GB
            let file_size = std::fs::metadata(&markers_table)
                .map(|m| m.len())
                .unwrap_or(0);
            let streaming = file_size > 2_000_000_000;
            if streaming {
                log::info!("Large file ({}GB), using streaming mode", file_size / 1_000_000_000);
            }
            commands::depth::run(&commands::depth::DepthParams {
                markers_table_path: markers_table,
                popmap_file_path: popmap,
                output_file_path: output_file,
                min_frequency,
                streaming,
            })
        }

        #[cfg(feature = "map")]
        Commands::Map {
            markers_file,
            output_file,
            popmap,
            genome_file,
            min_depth,
            ref groups,
            min_quality,
            min_frequency,
            signif_threshold,
            disable_correction,
        } => {
            let (g1, g2) = extract_groups(groups);
            commands::map::run(&commands::map::MapParams {
                markers_table_path: markers_file,
                popmap_file_path: popmap,
                genome_file_path: genome_file,
                output_file_path: output_file,
                min_depth,
                min_quality,
                min_frequency,
                signif_threshold,
                correction: if disable_correction { rsx_core::test_method::CorrectionMethod::None } else { rsx_core::test_method::CorrectionMethod::Bonferroni },
                test_method: rsx_core::test_method::TestMethod::ChiSquared,
                output_bayes: false,
                group1: g1,
                group2: g2,
            })
        }

        Commands::Subset {
            markers_table,
            popmap,
            output_file,
            min_depth,
            ref groups,
            signif_threshold,
            disable_correction,
            output_fasta,
            min_group1,
            min_group2,
            max_group1,
            max_group2,
            min_individuals,
            max_individuals,
        } => {
            let (g1, g2) = extract_groups(groups);
            commands::subset::run(&commands::subset::SubsetParams {
                markers_table_path: markers_table,
                popmap_file_path: popmap,
                output_file_path: output_file,
                min_depth,
                signif_threshold,
                correction: if disable_correction { rsx_core::test_method::CorrectionMethod::None } else { rsx_core::test_method::CorrectionMethod::Bonferroni },
                test_method: rsx_core::test_method::TestMethod::ChiSquared,
                output_bayes: false,
                output_fasta,
                group1: g1,
                group2: g2,
                min_group1,
                min_group2,
                max_group1,
                max_group2,
                min_individuals,
                max_individuals,
            })
        }

        Commands::Merge {
            input_files,
            output_file,
            buffer_size,
            output_parquet,
        } => commands::merge::run(&commands::merge::MergeParams {
            input_files,
            buffer_size: Some(buffer_size),
            output_file_path: output_file,
            output_parquet,
        }),

        Commands::Pca {
            markers_table,
            output_dir,
            min_depth,
            components,
        } => commands::pca::run(&commands::pca::PcaParams {
            markers_table_path: markers_table,
            output_dir,
            min_depth,
            n_components: components,
        }),
    };

    if let Err(e) = result {
        log::error!("{e}");
        std::process::exit(1);
    }
}
