[workspace]
name = "rsx-scripts"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64"]

[dependencies]
python = ">=3.11"
sympy = "*"
numpy = "*"
clangxx = "*"
clang = "*"
autoconf = "*"
automake = "*"
libtool = "*"
pkg-config = "*"
gmp = "*"
mpfr = "*"
mpfi = "*"
libxml2 = "*"
libxml2-devel = "*"
fplll = "*"
make = "*"
zlib = "*"
xz = "*"

[tasks]
derive = "python sympy/chi2_cdf_derivation.py"
