// GPL-3.0-or-later
// Copyright 2024--present rsx-rs developers

//! C-compatible FFI entry points.
//!
//! These functions are exported with `extern "C"` linkage and use
//! `#[repr(C)]` types. The C header is auto-generated by cbindgen.

pub mod commands;
pub mod types;
